spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/dictionary
    username: postgres
    password: 1234
    driver-class-name: org.postgresql.Driver
server:
  port: 8082
management:
  endpoints:
    web:
      exposure:
        include: health, info, prometheus # Включаем нужные endpoint'ы
      base-path: /actuator
  prometheus:
    metrics:
      export:
        enabled: true