spring:
  application:
    name: lc-dictionary
  datasource:
    url: jdbc:postgresql://localhost:5432/dictionary
    username: postgres
    password: 1234
    driver-class-name: org.postgresql.Driver
server:
  port: 8082